# Generated by Django 5.2.1 on 2025-05-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options_news_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
